language: node_js
node_js:
  - "6"
before_script: npm run build-inject
env:
  - BROWSER_NAME=chrome BROWSER_VERSION=latest
  - BROWSER_NAME=iphone BROWSER_VERSION=latest
  - BROWSER_NAME=android BROWSER_VERSION=latest
