language: node_js
node_js:
  - "6"
before_script:
  - npm run typings:install
  - npm run typings:install:test
  - npm run build:inject
test:
  - npm run lint
  - npm run lint:test
  - npm test
env:
  - BROWSER_NAME=chrome BROWSER_VERSION=latest
  - BROWSER_NAME=iphone BROWSER_VERSION=latest
  - BROWSER_NAME=android BROWSER_VERSION=latest
