language: node_js
node_js:
- '6'
addons:
  # https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
- npm run test:typings:install
script:
- npm run test:lint
- npm run test
env:
  global:
  - CXX=g++-4.8
