language: node_js
node_js:
  - '6'

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
  matrix:
    - KARMA_BROWSER=bs_ios_9_1
    - KARMA_BROWSER=bs_android_5_0

    # uneeded
    # - KARMA_BROWSER=bs_chrome
    # not working
    # - KARMA_BROWSER=bs_android_4_4
before_script:
  - npm run test:typings:install
script:
  - npm run test:lint
  - npm run test

# doesn't help that much with speed, maybe saves 40 seconds, and potentially
# introduces some more bugs
# cache:
#   directories:
#     - node_modules
