language: node_js
before_script: npm run build-inject
matrix:
  include:
    - env: BROWSER_NAME=chrome BROWSER_VERSION=latest
    - env: BROWSER_NAME=iphone BROWSER_VERSION=latest
    - env: BROWSER_NAME=android BROWSER_VERSION=latest
